env:
    GH_TOKEN: ENCRYPTED[2e4305c44355ef6f973814b1e9eb018a6c7628749e7325172773a1ec5868eadbc53332478cf3a54c80e149eda2465bfb]

task:
  name: LLVM Toolchain
  timeout_in: 480m  
  container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
      cpu: 8
      memory: 32G
        
  Get-deps_script:
       - bash ci.sh deps
  
  Deploy-builder_script:
      - bash build.sh
