on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 11 * * 4'
name: LLVM Toolchain
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v3

      - name: Get deps
        run: bash ci.sh deps

      - name: Deploy builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bash build.sh
